'use client';
import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';

export default function Reports() {
  const router = useRouter();
  const [clientName, setClientName] = useState('');
  const [revision, setRevision] = useState('');
  const [darkMode, setDarkMode] = useState(true);
  const [menuOpen, setMenuOpen] = useState(false);
  const [handoverSent, setHandoverSent] = useState(false);

  useEffect(() => {
    setClientName(localStorage.getItem('client') || 'Client');
    setRevision(localStorage.getItem('revision') || 'Revision');
    const saved = localStorage.getItem('darkMode');
    if (saved !== null) setDarkMode(saved === 'true');
  }, []);

  function toggleDark() {
    const next = !darkMode;
    setDarkMode(next);
    localStorage.setItem('darkMode', String(next));
  }

  const th = darkMode ? {
    bg: '#080C0F', surface: '#0E1419', surface2: '#141B22',
    border: '#1E2A35', textPrimary: '#E8EDF2', textSecondary: '#5A7080', textMuted: '#2E4050',
  } : {
    bg: '#F4F6F8', surface: '#FFFFFF', surface2: '#EDF0F3',
    border: '#D8DEE5', textPrimary: '#0D1318', textSecondary: '#4A5D6B', textMuted: '#8FA0AE',
  };

  // Auto-generate handover content from task data
  const now = new Date();
  const shiftDate = now.toLocaleDateString('en-AU', { day: '2-digit', month: 'short', year: 'numeric' });
  const shiftTime = now.toLocaleTimeString('en-AU', { hour: '2-digit', minute: '2-digit' });
  const shiftType = now.getHours() >= 6 && now.getHours() < 18 ? 'Day Shift' : 'Night Shift';
  const nextShift = shiftType === 'Day Shift' ? 'Night Shift' : 'Day Shift';

  const handoverText = `SHUTDOWN HANDOVER REPORT
${revision} — ${clientName}
${shiftDate} | ${shiftTime} | ${shiftType} to ${nextShift} Handover
Generated by Sentient Execution Intelligence

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

LAST 12 HOURS — SUMMARY
- 3 tasks completed this shift: T-001 Isolation & Lockout, T-002 Vessel Internal Inspection, T-010 Gearbox Oil Change
- 3 tasks currently in progress: T-003 Main Drive Bearing Replacement (62%), T-004 Conveyor Belt Tensioner Service (40%), T-007 Electrical Panel Upgrade (75%)
- 2 tasks delayed: T-005 SAG Mill Liner Change, T-006 Pump Station Overhaul
- Overall schedule deficit: -22.4 hrs behind planned

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

DELAYS & ISSUES
- T-005 SAG Mill Liner Change — currently 28% complete, delayed due to equipment availability. Downstream impact on T-008 Crusher Jaw Plate Swap and T-012 Final Commissioning.
- T-006 Pump Station Overhaul — currently 10% complete, delayed due to parts delivery. Downstream impact on T-009 Tailings Line Flush & Test.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

FOCUS AREAS FOR INCOMING SHIFT
1. Priority: Accelerate T-005 SAG Mill Liner Change — critical path task, directly impacts shutdown end date.
2. Complete T-003 Main Drive Bearing Replacement — 62% complete, target completion within next 8 hours.
3. Monitor T-006 Pump Station Overhaul — escalate parts delivery if no resolution within 2 hours.
4. Progress T-007 Electrical Panel Upgrade to completion — 75% complete.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

OVERALL SHUTDOWN STATUS
Total Tasks: 248 | Complete: 91 (37%) | In Progress: 44 | Delayed: 12 | Yet To Start: 101
Schedule Deficit: -22.4 hrs | Projected End Date: AT RISK

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by Sentient — Execution Intelligence
${revision} | ${clientName} | ${shiftDate} ${shiftTime}`;

  function sendViaOutlook() {
    const subject = encodeURIComponent(`Shutdown Handover Report — ${revision} | ${clientName} | ${shiftDate} ${shiftTime}`);
    const body = encodeURIComponent(handoverText);
    window.location.href = `mailto:?subject=${subject}&body=${body}`;
    setHandoverSent(true);
    setTimeout(() => setHandoverSent(false), 3000);
  }

  const menuItems = [
    { label: 'Overview', icon: 'M3 9l9-7 9 7v11a2 2 0 01-2 2H5a2 2 0 01-2-2z', path: '/overview' },
    { label: 'Dashboard', icon: 'M3 3h18v18H3zM3 9h18M9 3v18', path: '/dashboard' },
    { label: 'Vendor Setup', icon: 'M10 13a5 5 0 007.54.54l3-3a5 5 0 00-7.07-7.07l-1.72 1.71M14 11a5 5 0 00-7.54-.54l-3 3a5 5 0 007.07 7.07l1.71-1.71', path: '/vendor-setup' },
  ];

  return (
    <>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Syne:wght@400;700;800&family=DM+Mono:wght@400;500&display=swap');
        *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
        body { background: ${th.bg}; }
        body::before {
          content: '';
          position: fixed; inset: 0;
          background-image:
            linear-gradient(rgba(46,204,154,0.025) 1px, transparent 1px),
            linear-gradient(90deg, rgba(46,204,154,0.025) 1px, transparent 1px);
          background-size: 48px 48px;
          pointer-events: none; z-index: 0;
        }
        .menu-item:hover { background: ${th.surface2} !important; }
        .menu-item-danger:hover { background: rgba(224,90,90,0.08) !important; }
        @keyframes fadeIn { from{opacity:0;transform:translateY(8px)} to{opacity:1;transform:translateY(0)} }
      `}</style>

      <div style={{ position: 'relative', zIndex: 1, minHeight: '100vh', display: 'flex', flexDirection: 'column', fontFamily: "'DM Mono', monospace", color: th.textPrimary, background: th.bg }}
        onClick={() => setMenuOpen(false)}>

        {/* Header */}
        <header style={{ padding: '20px 32px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderBottom: `1px solid ${th.border}`, flexShrink: 0, background: th.surface }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            <div style={{ width: 24, height: 24, border: '1.5px solid #2ECC9A', borderRadius: 5, display: 'grid', placeItems: 'center', background: 'rgba(46,204,154,0.1)' }}>
              <svg width="12" height="12" viewBox="0 0 16 16" fill="none" stroke="#2ECC9A" strokeWidth="1.5">
                <path d="M8 2L14 5.5V10.5L8 14L2 10.5V5.5L8 2Z"/>
                <circle cx="8" cy="8" r="2" fill="#2ECC9A" stroke="none"/>
              </svg>
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 0 }}>
              <span style={{ fontFamily: "'Syne', sans-serif", fontSize: 14, fontWeight: 800, letterSpacing: '0.12em', textTransform: 'uppercase', lineHeight: 1.1, color: th.textPrimary }}>
                Sentient <span style={{ color: th.textMuted, fontWeight: 400 }}>|</span> {clientName}
              </span>
              <span style={{ fontFamily: "'Syne', sans-serif", fontSize: '6px', fontWeight: 700, letterSpacing: '0.32em', textTransform: 'uppercase', color: '#2ECC9A', whiteSpace: 'nowrap' }}>Execution Intelligence</span>
            </div>
          </div>

          <div style={{ position: 'relative' }}>
            <button onClick={(e) => { e.stopPropagation(); setMenuOpen(!menuOpen); }}
              style={{ padding: '8px 10px', background: 'transparent', border: `1px solid ${th.border}`, borderRadius: 6, color: th.textSecondary, cursor: 'pointer', display: 'flex', alignItems: 'center' }}>
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <line x1="3" y1="6" x2="21" y2="6"/>
                <line x1="3" y1="12" x2="21" y2="12"/>
                <line x1="3" y1="18" x2="21" y2="18"/>
              </svg>
            </button>
            {menuOpen && (
              <div onClick={e => e.stopPropagation()} style={{ position: 'fixed', top: 60, right: 20, background: th.surface, border: `1px solid ${th.border}`, borderRadius: 8, padding: 6, minWidth: 200, zIndex: 99999, boxShadow: '0 16px 48px rgba(0,0,0,0.3)', display: 'flex', flexDirection: 'column', gap: 2 }}>
                {menuItems.map(item => (
                  <div key={item.label} className="menu-item"
                    onClick={() => { if (item.path) router.push(item.path); }}
                    style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '9px 12px', borderRadius: 5, fontFamily: "'Syne', sans-serif", fontSize: 10, fontWeight: 700, letterSpacing: '0.12em', textTransform: 'uppercase', color: th.textSecondary, cursor: 'pointer' }}>
                    <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d={item.icon}/></svg>
                    {item.label}
                  </div>
                ))}
                <div style={{ height: 1, background: th.border, margin: '4px 0' }}></div>
                <div className="menu-item menu-item-danger" onClick={() => router.push('/')}
                  style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '9px 12px', borderRadius: 5, fontFamily: "'Syne', sans-serif", fontSize: 10, fontWeight: 700, letterSpacing: '0.12em', textTransform: 'uppercase', color: '#E05A5A', cursor: 'pointer' }}>
                  <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M9 21H5a2 2 0 01-2-2V5a2 2 0 012-2h4M16 17l5-5-5-5M21 12H9"/></svg>
                  New Session
                </div>
                <div style={{ height: 1, background: th.border, margin: '4px 0' }}></div>
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '8px 12px' }} onClick={e => e.stopPropagation()}>
                  <span style={{ fontFamily: "'Syne', sans-serif", fontSize: 10, fontWeight: 700, letterSpacing: '0.12em', textTransform: 'uppercase', color: th.textSecondary }}>{darkMode ? 'Dark Mode' : 'Light Mode'}</span>
                  <div onClick={toggleDark} style={{ width: 40, height: 22, background: darkMode ? th.surface2 : 'rgba(46,204,154,0.15)', border: `1px solid ${darkMode ? th.border : '#2ECC9A'}`, borderRadius: 100, position: 'relative', cursor: 'pointer', transition: 'all 0.3s' }}>
                    <div style={{ position: 'absolute', top: 2, left: darkMode ? 2 : 20, width: 16, height: 16, borderRadius: '50%', background: darkMode ? th.textMuted : '#2ECC9A', transition: 'all 0.3s' }}></div>
                  </div>
                </div>
              </div>
            )}
          </div>
        </header>

        {/* Main */}
        <main style={{ flex: 1, padding: '32px', display: 'flex', flexDirection: 'column', gap: 24 }}>

          {/* Page title */}
          <div>
            <div style={{ fontSize: 9, letterSpacing: '0.25em', textTransform: 'uppercase', color: '#2ECC9A', display: 'flex', alignItems: 'center', gap: 8, marginBottom: 10 }}>
              <div style={{ width: 16, height: 1, background: '#2ECC9A' }}></div>
              Reports
            </div>
            <div style={{ fontFamily: "'Syne', sans-serif", fontSize: 28, fontWeight: 800, letterSpacing: '-0.02em', lineHeight: 1.1, color: th.textPrimary }}>
              Shutdown <span style={{ color: '#2ECC9A' }}>Reporting</span>
            </div>
          </div>

          {/* Two report cards */}
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 20 }}>

            {/* Shift Handover */}
            <div style={{ background: th.surface, border: `1px solid ${th.border}`, borderRadius: 10, display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
              <div style={{ padding: '20px 24px', borderBottom: `1px solid ${th.border}` }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}>
                  <div style={{ width: 6, height: 6, borderRadius: '50%', background: '#2ECC9A', boxShadow: '0 0 6px #2ECC9A' }}></div>
                  <span style={{ fontFamily: "'Syne', sans-serif", fontSize: 11, fontWeight: 700, letterSpacing: '0.15em', textTransform: 'uppercase', color: th.textPrimary }}>Shift Handover</span>
                </div>
                <div style={{ fontSize: 10, color: th.textSecondary, lineHeight: 1.6 }}>
                  Auto-generated {shiftType} to {nextShift} handover report. Ready to send via Outlook.
                </div>
                <div style={{ marginTop: 10, display: 'flex', gap: 8 }}>
                  <span style={{ padding: '2px 10px', background: th.surface2, border: `1px solid ${th.border}`, borderRadius: 100, fontFamily: "'Syne', sans-serif", fontSize: 8, fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase', color: th.textSecondary }}>{shiftDate}</span>
                  <span style={{ padding: '2px 10px', background: th.surface2, border: `1px solid ${th.border}`, borderRadius: 100, fontFamily: "'Syne', sans-serif", fontSize: 8, fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase', color: th.textSecondary }}>{shiftTime}</span>
                  <span style={{ padding: '2px 10px', background: 'rgba(46,204,154,0.1)', border: '1px solid rgba(46,204,154,0.2)', borderRadius: 100, fontFamily: "'Syne', sans-serif", fontSize: 8, fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase', color: '#2ECC9A' }}>{shiftType}</span>
                </div>
              </div>

              {/* Preview */}
              <div style={{ flex: 1, padding: '16px 24px', overflowY: 'auto', maxHeight: 320 }}>
                <pre style={{ fontFamily: "'DM Mono', monospace", fontSize: 10, color: th.textSecondary, lineHeight: 1.8, whiteSpace: 'pre-wrap', wordBreak: 'break-word' }}>
                  {handoverText}
                </pre>
              </div>

              {/* Send button */}
              <div style={{ padding: '16px 24px', borderTop: `1px solid ${th.border}` }}>
                <button
                  onClick={sendViaOutlook}
                  style={{ width: '100%', padding: '12px', background: '#2ECC9A', border: 'none', borderRadius: 8, color: '#040D0A', fontFamily: "'Syne', sans-serif", fontSize: 11, fontWeight: 700, letterSpacing: '0.15em', textTransform: 'uppercase', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8 }}>
                  <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"/><polyline points="22,6 12,13 2,6"/></svg>
                  {handoverSent ? '✓ Opening Outlook...' : 'Send via Outlook'}
                </button>
              </div>
            </div>

            {/* Post Shutdown Report */}
            <div style={{ background: th.surface, border: `1px solid ${th.border}`, borderRadius: 10, display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
              <div style={{ padding: '20px 24px', borderBottom: `1px solid ${th.border}` }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}>
                  <div style={{ width: 6, height: 6, borderRadius: '50%', background: th.textMuted }}></div>
                  <span style={{ fontFamily: "'Syne', sans-serif", fontSize: 11, fontWeight: 700, letterSpacing: '0.15em', textTransform: 'uppercase', color: th.textPrimary }}>Post Shutdown Report</span>
                </div>
                <div style={{ fontSize: 10, color: th.textSecondary, lineHeight: 1.6 }}>
                  Full shutdown summary covering planned vs actual performance, delays, resolutions and final outcomes.
                </div>
              </div>

              <div style={{ flex: 1, padding: '32px 24px', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 12, opacity: 0.5 }}>
                <svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke={th.textMuted} strokeWidth="1.5">
                  <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z"/>
                  <polyline points="14 2 14 8 20 8"/>
                  <line x1="16" y1="13" x2="8" y2="13"/>
                  <line x1="16" y1="17" x2="8" y2="17"/>
                  <polyline points="10 9 9 9 8 9"/>
                </svg>
                <div style={{ fontFamily: "'Syne', sans-serif", fontSize: 11, fontWeight: 700, letterSpacing: '0.1em', color: th.textSecondary, textAlign: 'center' }}>Available at shutdown completion</div>
                <div style={{ fontSize: 10, color: th.textMuted, textAlign: 'center', lineHeight: 1.6 }}>This report is generated once all tasks are marked complete.</div>
              </div>

              <div style={{ padding: '16px 24px', borderTop: `1px solid ${th.border}` }}>
                <button
                  disabled
                  style={{ width: '100%', padding: '12px', background: th.surface2, border: `1px solid ${th.border}`, borderRadius: 8, color: th.textMuted, fontFamily: "'Syne', sans-serif", fontSize: 11, fontWeight: 700, letterSpacing: '0.15em', textTransform: 'uppercase', cursor: 'not-allowed', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8 }}>
                  <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z"/><polyline points="14 2 14 8 20 8"/></svg>
                  Load Post Shutdown Report
                </button>
                <div style={{ fontSize: 9, color: th.textMuted, textAlign: 'center', marginTop: 6, letterSpacing: '0.1em', textTransform: 'uppercase' }}>Available once shutdown is complete</div>
              </div>
            </div>

          </div>
        </main>

        <footer style={{ padding: '12px 32px', borderTop: `1px solid ${th.border}`, display: 'flex', justifyContent: 'space-between', flexShrink: 0, background: th.surface }}>
          <span style={{ fontSize: 10, color: th.textMuted, letterSpacing: '0.1em' }}>SENTIENT V0.1 — MVP</span>
          <span style={{ fontSize: 10, color: th.textMuted, letterSpacing: '0.1em' }}>SHUTDOWN PLANNING & EXECUTION PLATFORM</span>
        </footer>

      </div>
    </>
  );
}